### PR TITLE
Remove namespace pollution

### PR DESCRIPTION
**Pull request by camillescott**
Currently, gfakluge and it's dependencies pollute the global namespace by having `using namespace std` in header files. This is the first of a few pull's to remove that.

### CODE REVIEW

**Comment by edawson** [comment]
This has been a problem for a while and I've been too slammed with my thesis to do the right thing and fix all the backing libraries. I really appreciate the PR! Happy to help as a I can if you can point me in the right direction - I assume tinyFA also needs the same treatment.

**Comment by camillescott** [comment]
No problem! TinyFA actually seems to be free of it, though gfakluge proper has a ton in it. I fixed it all last night though, so PR should be up soon :)

**Comment by edawson** [comment]
This looks good - there might still be some issues with size_t around, but I'll fix those in a branch.

Thank you so much for patching this up!

**Comment by cartoonist** [comment]
Hello there,

Regarding converting `int` to `size_t`, I guess that the reason is the size of the `int` type. However, another issue that arises with this PR is that `size_t` is unsigned integer while the type of variable `len` is signed. As you know, comparing a signed and unsigned could be problematic, since the compiler converts the signed one to `unsigned int` (to be more clear, if `len` is equal to -1, it will be converted to `UINT_MAX` when the expression `i < len` is evaluated. So, `i` in the for loop gets the values from 0 to `UINT_MAX - 1` while the for loop should not be executed).

**Comment by cartoonist** [comment]
There was also a bug fixed in #2 which was reverted by this PR ([pliib.hpp:286](https://github.com/edawson/pliib/pull/3/files#diff-771d10ebc391fe7066fdfd7b56d79bc8R286)). There should be `&&` instead of comma `,` operator.

**Comment by cartoonist** [comment]
I reintroduced the fix in PR #4.

**Comment by edawson** [comment]
I'm going to try to merge these all this week now that I'm almost done with phd corrections. Many thanks to y'all for the contributions!

**Pull request merged**
